### ISSUE TITLE
App crashes after going to the article detail view and coming back to list view and scrolling

### ISSUE THREAD

**Issue by anirvan-majumdar** [nikhil-31/HackerNewsFirebaseApp#1]
See stacktrace below:
```
02-06 12:34:56.425 4197-4197/in.co.nikhil.hackernewsfirebaseapp E/AndroidRuntime: FATAL EXCEPTION: main
Process: in.co.nikhil.hackernewsfirebaseapp, PID: 4197
io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 16307898
  at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:664)
  at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:449)
  at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:387)
  at io.realm.Realm.createObjectInternal(Realm.java:864)
  at io.realm.Realm.createObject(Realm.java:844)
  at in.co.nikhil.hackernewsfirebaseapp.activity.MainActivity$4.onResponse(MainActivity.java:175)
  at in.co.nikhil.hackernewsfirebaseapp.activity.MainActivity$4.onResponse(MainActivity.java:163)
  at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
  at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
  at android.os.Handler.handleCallback(Handler.java:790)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6494)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by nikhil-31** [comment]
Hi,

This is strange, never encountered it before will test and fix tonight .

**Comment by nikhil-31** [comment]
Hi,

I am unable to recreate this problem, i tried manually, i also tested with the monkey UI/Application Exerciser Monkey with 10000 events and there was no crash.
Edit -  tried with 20000 as well no error found 

I will leave this open please update if this appears again. Seems like this is a one-off problem.

**Comment by nikhil-31** [comment]
This error will no longer occur,  changed realm to copyandupdate. Closing issue
